codigo_Equipo = input("Ingrese el codigo del equipo: ")
Marca = input("Ingrese la marca del equipo: ")
Procesador = input("Ingrese el procesador del equipo: ")
Memoria_RAM = input("Ingrese la memoria RAM del equipo: ")
Capacidad_del_equipo = input("Ingrese la capacidad del equipo: ")
sistema_operativo = input("Ingrese el sistema operativo del equipo: ")
estado_del_equipo = input("Ingrese el estado del equipo: ")

print("Código del equipo: ", codigo_Equipo)
print("Marca del equipo: ", Marca)
print("Procesador del equipo: ", Procesador)
print("Memoria RAM del equipo: ", Memoria_RAM)
print("Capacidad del equipo: ", Capacidad_del_equipo)
print("Sistema operativo del equipo: ", sistema_operativo)
print("Estado del equipo: ", estado_del_equipo)
