nombre_Estudiante = input("Ingrese su Nombre: ")
apellido_Estudiante = input("Ingrese su Apellido: ")
edad = int(input("Ingrese su Edad: "))
ciudad = input("Ingrese su Ciudad: ")
universidad = input("Ingrese su Universidad: ")
carrera = input("Ingrese su Carrera: ")
semestre = int(input("Ingrese su Semestre: "))
promedio = float(input("Ingrese su Promedio: "))

print("\n========== PERFIL DEL ESTUDIANTE ==========")
print("Nombre completo: ", nombre_Estudiante, apellido_Estudiante)
print("Edad: ", edad)
print("Ciudad: ", ciudad)
print("Universidad: ", universidad)
print("Carrera: ", carrera)
print("Semestre: ", semestre)
print("Promedio: ", promedio)
print("===========================================\n")

print("¡Ahora es tu turno de identificar los tipos de datos!")
print("¿Qué variables de las que ingresaste pertenecen a los siguientes tipos?")
print("- str (Nombre, Apellido, Ciudad, Universidad, Carrera)")
print("- int (Edad, Semestre)")
print("- float (Promedio)")
print("- bool (Ninguna)")
